[project]
name = "prjkcad-backend"
version = "0.1.0"
description = "Text2CAD Studio Backend API"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]",
    "fastapi-cli",
    "uvicorn[standard]",
    "pydantic",
    "torch",
    "transformers",
    "trimesh",
    "scipy",
    "numpy",
    "python-multipart",
    "Pillow"
]

[tool.fastapi]
entrypoint = "main:app"
