run_name: baseline_text2cad
type: text2cad
data:
  data_folder: data/text2cad
  metadata_csv: data/text2cad/text2cad_v1.1.csv
  split_json: data/text2cad/train_test_val.json
  source_data_type: text2cad
  is_cmdonly: false
  sample_ratio: 1.0
  eval_split_ratio: 0.1
  num_workers: 4
  description_level: expert
  batch_size: 8
  max_samples: null
tokenizer:
  source: huggingface
  model_name: bert-base-uncased
model:
  is_pretrained: true
  encoder_type: bert
  cmd_decoder_type: sdpa
  is_cmd_only: false
  args_decoder_type: sdpa
  d_model: 256
  max_new_cmds: 1024
  moe_conf: null
  adaptive_layer: sdpa
  cmd_embedding_type: rope_sdpa
  args_embedding_type: rope_sdpa
  use_drop_out: true
  drop_out_p: 0.1
  freeze_encoder: true
trainer:
  optimizer: AdamW
  optimizer_kwargs:
    lr: 1.0e-04
    weight_decay: 0.01
  criterion:
    source: local
    cls: Text2CADCriterion
    kwargs:
      lambda_args: 1.0
  epochs: 24
  max_new_cmds: 1024
  eval_steps: 25000
  scheduler:
    warmup_ratio: 0.05
  kwargs:
    teacher_forcing_ratio: 1.0
    max_grad_norm: 1.0
pretrained_path: out/pretrain
random_seed: 42
