run_name: experiment_1a
data:
  data_root: data/text2cad
  source_data_type: text2cad
  is_cmdonly: false
  sample_ratio: 0.01
  eval_split_ratio: 0.2
  num_workers: 4
  description_level: expert
  batch_size: 16
  max_samples: 100000
tokenizer:
  source: huggingface
  model_name: bert-base-uncased
model:
  is_pretrained: false
  encoder_type: bert
  cmd_decoder_type: torch
  is_cmd_only: false
  args_decoder_type: sdpa
  d_model: 512
  max_new_cmds: 128
  moe_conf: null
  adaptive_layer: sdpa
  cmd_embedding_type: rope_sdpa
  args_embedding_type: rope_sdpa
  use_drop_out: true
  drop_out_p: 0.3
  freeze_encoder: true
trainer:
  optimizer: AdamW
  optimizer_kwargs:
    lr: 1.0e-04
    weight_decay: 0.01
  criterion:
    source: local
    cls: DualSeqCriterion
    kwargs:
      lambda_after_pad: 3
      lambda_overgen: 3
  epochs: 100
  max_new_cmds: 128
  kwargs:
    teacher_forcing_ratio: 1.0
    max_grad_norm: 1.0
    quant_type: fp16
pretrained_path: out/experiment_1a/checkpoint.pt
random_seed: 42
