run_name: m3-overfit-test
type: fine_tune
data:
  data_folder: data/text2cad
  metadata_csv: data/text2cad/text2cad_v1.1.csv
  split_json: data/text2cad/train_test_val.json
  source_data_type: text2cad
  is_cmdonly: false
  sample_ratio: 1.0
  val_sample_ratio: 0.0
  eval_split_ratio: 0.0
  num_workers: 4
  description_level: expert
  batch_size: 16
  max_samples: 128
  random_sample: true
tokenizer:
  source: huggingface
  model_name: bert-base-uncased
model:
  is_pretrained: true
  encoder_type: bert
  cmd_decoder_type: sdpa
  is_cmd_only: false
  args_decoder_type: sdpa
  d_model: 512
  max_new_cmds: 128
  moe_conf: null
  adaptive_layer: sdpa
  cmd_embedding_type: rope_sdpa
  args_embedding_type: rope_sdpa
  use_drop_out: true
  drop_out_p: 0.5
  freeze_encoder: true
  out_type: EightBitBinarizedArgs
  use_cmd_args_fusion: true
  n_dec_blocks: 6
trainer:
  optimizer: AdamW
  optimizer_kwargs:
    lr: 3.0e-04
    weight_decay: 0.01
    betas: [0.9, 0.98]
  criterion:
    source: local
    cls: EightBitBinarizedArgsCriterion
    kwargs:
      lambda_args: 1.0
      label_smoothing: 0.0
      eos_weight: 5.0
      lambda_structural: 0.1
  epochs: 200
  max_new_cmds: 128
  eval_steps: 1000000
  scheduler:
    type: cosine
    warmup_ratio: 0.05
    eta_min: 0.01
  kwargs:
    teacher_forcing_ratio: 1.0
    max_grad_norm: 1.0
    quant_type: fp16
random_seed: 42
pretrained_path: out/m3-xx/checkpoint.pt
use_wandb: true
