data:
  batch_size: 4
  data_root: data/text2cad
  description_level: expert
  eval_split_ratio: 0.2
  is_cmdonly: false
  max_samples: 16
  num_workers: 4
  sample_ratio: 1.0
  source_data_type: text2cad
grpo:
  clip_eps: 0.2
  eval_fraction: 0.1
  max_cd: 0.5
  min_cd: 1.0e-05
  n_rollouts: 4
  temperature: 1.0
model:
  adaptive_layer: sdpa
  args_decoder_type: sdpa
  args_embedding_type: rope_sdpa
  cmd_decoder_type: torch
  cmd_embedding_type: rope_sdpa
  d_model: 512
  drop_out_p: 0.3
  encoder_type: bert
  is_cmd_only: false
  is_pretrained: false
  max_new_cmds: 128
  moe_conf: null
  use_drop_out: true
random_seed: 42
run_name: grpo_test
tokenizer:
  model_name: bert-base-uncased
  source: huggingface
trainer:
  criterion:
    cls: DualSeqCriterion
    kwargs:
      lambda_after_pad: 3
      lambda_overgen: 3
    source: local
  epochs: 2
  eval_steps: 2
  max_new_cmds: 128
  optimizer: AdamW
  optimizer_kwargs:
    lr: 5.0e-06
    weight_decay: 0.01
type: grpo
