run_name: sanity_a
data:
    data_root: data/text2cad
    source_data_type: text2cad
    is_cmdonly: true
    sample_ratio: 0.01
    eval_split_ratio: 0.2
    num_workers: 4
    description_level: abstract
    batch_size: 16
    max_samples: 16

tokenizer:
    source: huggingface
    model_name: t5-small

model:
    source: local
    cls: T5EncT5DecCAD
    is_pretrained: false
    kwargs:
        pretrained_model_name: t5-small
        max_new_cmds: 84

trainer:
    optimizer: AdamW
    optimizer_kwargs:
        lr: 1.0e-4
        weight_decay: 1.0e-2
    criterion:
        source: local
        cls: DualSeqCMDOOnlyCriterion
        kwargs:
            lambda_after_pad: 3
            lambda_overgen: 3
    epochs: 2
    max_new_cmds: 84
    kwargs:
        teacher_forcing_ratio: 1
        max_grad_norm: 1.0

pretrained_path: null
random_seed: 42